### ISSUE TITLE
Difficulties

### ISSUE THREAD

**Issue by queiroga** [danwilson/social-auth-plugin#1]
Hi, Dan.

Did window.socialAuth.loginFacebook change to window.socialAuth.accessFacebook? It now has a third parameter: fields. What would that be?

I keep getting error when calling:

window.socialAuth.accessFacebook(function(data) {
            console.log('succes');
        }, function(error) {
            console.log('error' + error);
        });

Where could I find more about this plugin? The README file is pretty bare.

Thanks.

**Comment by danwilson** [comment]
I've updated the README with a section about setting up the apps on Twitter and Facebook's developer sites, which might be the issue.  The error messages that come back from the social authentication in iOS are not always crystal clear, which is why the plugin does not give clear messages.

The main things to check are:
1. You have an app set up on Facebook's developer website
2. The App ID there matches what you put in SocialAuthPlugin.m
3. The Bundle ID there matches what your iOS project has
4. On your test device/simulator you have a Facebook account enabled through Settings > Facebook.
5. If your app shows up in Settings > Facebook make sure that it is not toggled off.  If it does not show there it is also ok.

Also, yes accessFacebook was a last minute change that I did not update in the README by mistake.  The fields parameter is not used right now, but I added a message about it in the README as well for what it will mean when it is implemented.

Thanks
